version: '3.7'

services:
  frontend:
    image: employees-frontend:latest
    container_name: employees-frontend-app
    environment:
      - REACT_APP_BACKEND_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
